GET http://localhost:3000/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vZ2FhbiIsImlhdCI6MTcyMjcwNDk0MX0.2YQxXfioBk8dDpeacP_XAxmnyIIMwr81qVtDU7ziZ9g

###
post http://localhost:3000/register
Content-Type: application/json

{
    "username":"praveen",
    "firstname":"praveen",
    "lastname":"raj",
    "password":"raj@praveen",
    "email":"praveenraj12@gmail.com",
    "gender":"male"
}

###
post http://localhost:3000/login
Content-Type: application/json

{
    "username":"mogaan",
    "password":"mogan@rajini"
}

###
GET http://localhost:3000/menu
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vZ2FhbiIsImlhdCI6MTcyMjcwNDk0MX0.2YQxXfioBk8dDpeacP_XAxmnyIIMwr81qVtDU7ziZ9g


###
GET http://localhost:3000/menu?search_item=fish&category='Burger'
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vZ2FhbiIsImlhdCI6MTcyMjcwNDk0MX0.2YQxXfioBk8dDpeacP_XAxmnyIIMwr81qVtDU7ziZ9g

###
post http://localhost:3000/cart
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vZ2FhbiIsImlhdCI6MTcyMjcwNDk0MX0.2YQxXfioBk8dDpeacP_XAxmnyIIMwr81qVtDU7ziZ9g
Content-Type: application/json

{
    "items":4,
    "total_amount":1800,
    "cart_items":[
        {"id": 5, "itemName": "Chicken Burger", "category": "Burger", "price": 115, "foodLabel": "Non Veg"},
        {"category":"Pizza","foodLabel":"Non Veg","id":61, "itemName":"Chicken Pizza","mustTry":"", "price": 220, "quantity":2},
        {"id": 70, "itemName": "Spicy Juicy Chicken Momos", "category": "Fried Momos", "price": 120, "foodLabel": "Non Veg"},
        {"id": 3, "itemName": "Paneer Burger", "category": "Burger", "price": 115, "foodLabel": "Veg"}],
    "customer_location":"Puducherry"
}

###
get http://localhost:3000/order-history
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vZ2FhbiIsImlhdCI6MTcyMjcwNDk0MX0.2YQxXfioBk8dDpeacP_XAxmnyIIMwr81qVtDU7ziZ9g